version: '3'

services:
  fract:
    container_name: fract
    build:
      context: .
    restart: always
    environment:
      FRACTUS_YML: /host/fractus.yml
    volumes:
      - ${HOME}:/host
    command:
      - open
