---
version: '3'

services:
  fract:
    container_name: fract
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/fract:latest
    networks:
      - oanda-db
    depends_on:
      - oanda-cli
      - redis
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - fract
    command:
      - open
      - --file=/wd/fract.yml
      - --log-dir=./log_from_fract
      - --timeout=3600
      - --ignore-api-error
    restart: always
  oanda-cli:
    container_name: oanda-cli
    image: dceoy/oanda-cli:latest
    networks:
      - oanda-db
    depends_on:
      - redis
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - oanda-cli
    command:
      - stream
      - --file=/wd/fract.yml
      - --use-redis
      - --target=pricing
      - --timeout=3600
      - --ignore-api-error
      - --quiet
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - oanda-db
    volumes:
      - redis-data:/data
    restart: always

networks:
  oanda-db:
    external: false

volumes:
  redis-data:
